/**
 * @file chat-formatter.util.ts
 * @description Standalone utility functions for parsing and formatting AI chat responses and pagination metadata.
 * 
 * WHY THIS UTILITY EXISTS:
 * In Express MCP, LLM outputs often contain embedded metadata like usage statistics or multi-page table formatting.
 * Frontends or API consumers require standardized JSON structures containing array of content blocks.
 * Extracting these formatting rules into standalone utility functions promotes code reusability, modularity,
 * and testability without cluttering main server routes or LLM pipeline logic.
 */

/**
 * Interface representing standard content block emitted in chat API responses.
 */
export interface ContentBlock {
  type: "text";
  text: string;
}

/**
 * Interface representing structured response payload for chat endpoints.
 */
export interface FormattedChatResponse {
  content: ContentBlock[];
}

/**
 * Interface representing parsed pagination metadata from LLM output.
 */
export interface PaginationState {
  page: number;
  totalPages: number;
}

/**
 * Formats standard chat responses by stripping usage headers if present and returning a structured content block array.
 * 
 * WHY:
 * MCP clients expect `content: [{ type: "text", text: "..." }]` payloads.
 * If raw text starts with `[Usage: X/Y tokens | remaining: Z]`, this function splits usage metadata from the core message text.
 * 
 * @param text Raw text response generated by LLM processor.
 * @returns Structured object containing array of content blocks.
 * 
 * @example
 * formatChatResponse("[Usage: 500/20000 tokens]\n\nHello World")
 * // Returns: { content: [{ type: "text", text: "[Usage: 500/20000 tokens]" }, { type: "text", text: "Hello World" }] }
 */
export function formatChatResponse(text: string): FormattedChatResponse {
  const usageMatch = text.match(/^\[Usage: (.+)\]\s*\n\s*\n?(.*)$/s);
  if (!usageMatch) {
    return { content: [{ type: "text", text }] };
  }

  const usageText = `[Usage: ${usageMatch[1]}]`;
  const answerText = usageMatch[2]?.trim() || "";
  return {
    content: [
      { type: "text", text: usageText },
      ...(answerText ? [{ type: "text" as const, text: answerText }] : []),
    ],
  };
}

/**
 * Formats native assistant responses for REST API consumers.
 * 
 * WHY:
 * Similar to formatChatResponse, but removes square brackets from usage text to present clean human-readable output
 * suitable for web interfaces and chat widgets.
 * 
 * @param text Raw text response with optional embedded token usage prefix.
 * @returns Standardized formatted response payload.
 */
export function formatNativeAssistantResponse(text: string): FormattedChatResponse {
  const usageMatch = text.match(/^\[Usage: (.+)\]\s*\n\s*\n?(.*)$/s);
  if (!usageMatch) {
    return { content: [{ type: "text", text }] };
  }

  const usageText = `Usage: ${usageMatch[1]}`;
  const answerText = usageMatch[2]?.trim() || "";
  return {
    content: [
      { type: "text", text: usageText },
      ...(answerText ? [{ type: "text" as const, text: answerText }] : []),
    ],
  };
}

/**
 * Parses pagination metadata from database tool text output.
 * 
 * WHY:
 * When tool handlers return formatted tables containing string indicators like "Page 1 of 5",
 * this helper extracts numeric page indices to store session pagination state for subsequent "next page" user prompts.
 * 
 * @param text Raw text output returned by paginated MCP tool calls.
 * @returns Object containing current page number and total pages, or null if no pagination match found.
 */
export function parsePaginationState(text: string): PaginationState | null {
  const match = text.match(/Page\s+(\d+)\s+of\s+(\d+)/i);
  if (!match) return null;
  return {
    page: Number(match[1]),
    totalPages: Number(match[2]),
  };
}
